### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by nictait** [scraperwiki/code-scraper-in-browser-tool#134] opened 2014-08-02 11:29 UTC
Trouble saving code! mv: cannot move ‘code/scraper.new.25744’ to ‘code/scraper’: No space left on device

**Comment by StevenMaude** [comment] 2016-08-10 11:03
Think this is a duplicate of https://github.com/scraperwiki/code-scraper-in-browser-tool/issues/135.

Closing likewise since it shouldn't apply now.

**Closed by StevenMaude** 2016-08-10 11:03 UTC
